/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UITParking.TEST2;


import UITParking.BUS.KhachHangBUS;
import UITParking.BUS.NguoiDungBUS;
import UITParking.BUS.NhanVienBUS;
import UITParking.BUS.XeBUS;
import UITParking.DTO.KhachHangDTO;
import UITParking.DTO.NguoiDungDTO;
import UITParking.DTO.NhanVienDTO;
import UITParking.DTO.XeDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author ADMIN
 */
public class QLXJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLXJPanel
     */
    XeBUS xetbl = new XeBUS();
    ArrayList<XeDTO> list_XE = xetbl.getlist_XE();
    
    private DefaultTableModel model;
    private String[] columnHeaders = new String[]{"STT", "Mã Xe", "Tên Loại Xe", "Biển Số Xe"};

    private TableRowSorter<TableModel> rowSorter = null;

    public QLXJPanel() throws Exception {
        initComponents();
        initTable();
        hoTroTimKiem();
//        btnCapNhat.setEnabled(false);
//        btnXoa.setEnabled(false);
//        btnLuu.setEnabled(false);
    }

    public void resetRender() {
        txtMaXe.setText("");
        txtBienSoXe.setText("");
        txtTenLoaiXe.setText("");

    }

    public void initTable() throws Exception {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(columnHeaders);
        int index = 1;
        for (XeDTO xe : list_XE) {

            //Cập nhật bảng
            model.addRow(new Object[]{index, xe.getStrMaXe(),
                xe.getStrTenLoaiXe(),  xe.getStrBienSoXe()});
            index++;
        }

        tblXe.setModel(model);

    }

    public void hoTroTimKiem() {

        rowSorter = new TableRowSorter<>(tblXe.getModel());
        tblXe.setRowSorter(rowSorter);
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtTimKiem.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtTimKiem.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }

    //Hàm cập nhật lại bảng sau khi thêm xóa sửa
    public void capNhatLaiTable() {
        list_XE = xetbl.getlist_XE();
        model.setRowCount(0);
        int index = 1;
        for (XeDTO xe : list_XE) {
            //Cập nhật bảng
            model.addRow(new Object[]{index, xe.getStrMaXe(),
                xe.getStrTenLoaiXe(),  xe.getStrBienSoXe()});
            index++;
        }
        model.fireTableDataChanged();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        txtTenLoaiXe = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtBienSoXe = new javax.swing.JTextField();
        btnNhapMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblXe = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setText("Mã xe");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 64, 22));
        jPanel1.add(txtMaXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 232, -1));

        jLabel63.setText("Tên loại xe");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, -1));
        jPanel1.add(txtTenLoaiXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 230, -1));

        jLabel64.setText("Biển số xe");
        jLabel64.setToolTipText("");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 55, -1));
        jPanel1.add(txtBienSoXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 230, -1));

        btnNhapMoi.setText("Nhập mới");
        btnNhapMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapMoibtnNhapMoiMouseClicked(evt);
            }
        });
        jPanel1.add(btnNhapMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuubtnLuuMouseClicked(evt);
            }
        });
        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 57, -1));

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatbtnCapNhatMouseClicked(evt);
            }
        });
        jPanel1.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoabtnXoaMouseClicked(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiembtnTimKiemMouseClicked(evt);
            }
        });
        jPanel1.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 160, -1));

        tblXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblXetblNhanVienMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(tblXe);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, 974, 302));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapMoibtnNhapMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapMoibtnNhapMoiMouseClicked
        resetRender();
    }//GEN-LAST:event_btnNhapMoibtnNhapMoiMouseClicked

    private void btnLuubtnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuubtnLuuMouseClicked
        StringBuilder sb = new StringBuilder();
        if (txtMaXe.getText().equals("")) {
            sb.append("Mã xe không được để trống.");
            txtMaXe.setBackground(Color.red);
        } 
        if (xetbl.getInfor(txtMaXe.getText()) != null) {
            sb.append("Mã xe đã tồn tại.");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            XeDTO xe = new XeDTO();
            xe.setStrMaXe(txtMaXe.getText());
            xe.setStrTenLoaiXe(txtTenLoaiXe.getText());
            xe.setStrBienSoXe(txtBienSoXe.getText());
            xetbl.them(xe);
            

            //Cập nhật lại Table
            capNhatLaiTable();
            JOptionPane.showMessageDialog(this, "Xe mới đã được thêm vào CSDL");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuubtnLuuMouseClicked

    private void btnCapNhatbtnCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatbtnCapNhatMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtMaXe.getText().equals("")) {
            sb.append("Mã xe không được để trống.");
            txtMaXe.setBackground(Color.red);
        } else {
            txtMaXe.setBackground(Color.white);
        }
        if (xetbl.getInfor(txtMaXe.getText()) == null) {
            sb.append("Mã xe không tồn tại.");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            XeDTO xe = new XeDTO();
            xe.setStrMaXe(txtMaXe.getText());
            xe.setStrTenLoaiXe(txtTenLoaiXe.getText());
            xe.setStrBienSoXe(txtBienSoXe.getText());
            xetbl.sua(xe);
            //Cập nhật lại Table
            capNhatLaiTable();

            JOptionPane.showMessageDialog(this, "Xe đã được cập nhật vào CSDL");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatbtnCapNhatMouseClicked

    private void btnXoabtnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoabtnXoaMouseClicked
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtMaXe.getText().equals("")) {
            sb.append("Mã xe không được để trống.");
            txtMaXe.setBackground(Color.red);
        } else {
            txtMaXe.setBackground(Color.white);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            XeDTO xe = xetbl.getInfor(txtMaXe.getText());
            xetbl.xoa(xe);

            JOptionPane.showMessageDialog(this, "Xe đã xóa khỏi CSDL");

            //Reset lại render
            resetRender();

            //Cập nhật lại bảng
            capNhatLaiTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoabtnXoaMouseClicked

    private void btnTimKiembtnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiembtnTimKiemMouseClicked
        // TODO add your handling code here:
        if (txtMaXe.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã xe phải được nhập để tìm kiếm");
            return;
        }

        try {
            XeDTO xe = xetbl.getInfor(txtMaXe.getText());

            if (xe != null) {
                txtMaXe.setText(xe.getStrMaXe());
                txtTenLoaiXe.setText(xe.getStrTenLoaiXe());
                txtBienSoXe.setText(xe.getStrBienSoXe());
            } else {
                JOptionPane.showMessageDialog(this, "Xe không tìm thấy");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKiembtnTimKiemMouseClicked

    private void tblXetblNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXetblNhanVienMousePressed
        // TODO add your handling code here:
        resetRender();
        int selectedRow = tblXe.getSelectedRow();
        if (selectedRow >= 0) {

            XeDTO xe = list_XE.get(selectedRow);

            txtMaXe.setText(xe.getStrMaXe());
            txtTenLoaiXe.setText(xe.getStrTenLoaiXe());
            txtBienSoXe.setText(xe.getStrBienSoXe());
            
        }
    }//GEN-LAST:event_tblXetblNhanVienMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblXe;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtTenLoaiXe;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
