
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITParking.GUI;

import UITParking.BUS.KhachHangBUS;
import UITParking.BUS.NguoiDungBUS;
import UITParking.BUS.XeBUS;
import UITParking.DTO.KhachHangDTO;
import UITParking.DTO.NguoiDungDTO;
import UITParking.DTO.XeDTO;
import static UITParking.GUI.InitPublic.getConvertYYYYMMDD;
import static UITParking.GUI.DangNhap.pHoTen;
import static UITParking.GUI.DangNhap.pMaND;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class CapNhatThongTinKH extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatThongTinKH
     */
    NguoiDungBUS nguoidungtbl = new NguoiDungBUS();
    NguoiDungDTO nd = nguoidungtbl.getInfor(pMaND);
    KhachHangBUS khachhangtbl = new KhachHangBUS();
    XeBUS xetbl = new XeBUS();
    KhachHangDTO kh = khachhangtbl.getInfor(nd.getStrMaND());

    public CapNhatThongTinKH() throws Exception {
        initComponents();
        setIconImage();
        NguoiDungBUS nguoidungtbl = new NguoiDungBUS();
        NguoiDungDTO nd = nguoidungtbl.getInfor(pMaND);
        setAccount();
        //Không cho sửa Số dư
        tfdSoDu.setEnabled(false);
        tfdEmailAccount.setEnabled(false);
    }

    public void setAccount() {
        txtHoTenAccount.setText(nd.getStrHoTen());
        tfdHoTenAccount.setText(nd.getStrHoTen());
        tfdEmailAccount.setText(nd.getStrEmail());
        tfdDiachiAccount.setText(nd.getStrDiaChi());
        tfdQueQuanAccount.setText(nd.getStrQueQuan());
        tfdSDTAccount.setText(nd.getStrSDT());
        tfdSoDu.setText(String.valueOf(kh.getLongSoDu()));
        if (kh.getStrMaXe() != null) {
            XeDTO xe = xetbl.getInfor(kh.getStrMaXe());
            if (xe.getStrTenLoaiXe() != null) {
                if (xe.getStrTenLoaiXe().equals("Xe dap")) {
                    cbbLoaiXe.setSelectedItem("Xe đạp");
                }
                if (xe.getStrTenLoaiXe().equals("Xe may")) {
                    cbbLoaiXe.setSelectedItem("Xe máy");
                }
            }
            tfdBienSoXe.setText(xe.getStrBienSoXe());
        }

        if (nd.getStrGioiTinh() != null) {
            if (nd.getStrGioiTinh().equals("Nu")) {
                cbbGioiTinh.setSelectedItem("Nữ");
            }
            if (nd.getStrGioiTinh().equals("Nam")) {
                cbbGioiTinh.setSelectedItem("Nam");
            }
        }
        if (nd.getDateNgSinh() != null) {
            jdcNgaySinh.setDate(nd.getDateNgSinh());
        }

    }

    public void render() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHoTenAccount = new javax.swing.JLabel();
        btnThoatAccount = new javax.swing.JButton();
        btnHomeAccount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdQueQuanAccount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfdHoTenAccount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdEmailAccount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdBienSoXe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfdDiachiAccount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbbLoaiXe = new javax.swing.JComboBox<>();
        labelBienSoXe = new javax.swing.JLabel();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        btnHuyAccount = new javax.swing.JButton();
        btnCapNhatAccount = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfdSDTAccount = new javax.swing.JTextField();
        labelSoDu = new javax.swing.JLabel();
        tfdSoDu = new javax.swing.JTextField();
        labelLoaiXe = new javax.swing.JLabel();
        cbbGioiTinh = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UIT Parking");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_male_user_120px.png"))); // NOI18N

        txtHoTenAccount.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        txtHoTenAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtHoTenAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHoTenAccount.setText("Name");

        btnThoatAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btnThoatAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoatAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatAccountMouseClicked(evt);
            }
        });
        btnThoatAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatAccountActionPerformed(evt);
            }
        });

        btnHomeAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        btnHomeAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHomeAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeAccountMouseClicked(evt);
            }
        });
        btnHomeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHoTenAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThoatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHomeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHoTenAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHomeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 560));

        jLabel3.setFont(new java.awt.Font("Cooper", 1, 36)); // NOI18N
        jLabel3.setText("ACCOUNT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 210, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Quê quán");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 70, -1));

        tfdQueQuanAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdQueQuanAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdQueQuanAccountActionPerformed(evt);
            }
        });
        jPanel1.add(tfdQueQuanAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 240, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Họ tên");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 50, -1));

        tfdHoTenAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdHoTenAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdHoTenAccountActionPerformed(evt);
            }
        });
        jPanel1.add(tfdHoTenAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 240, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 50, -1));

        tfdEmailAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdEmailAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdEmailAccountActionPerformed(evt);
            }
        });
        jPanel1.add(tfdEmailAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 240, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 90, -1));

        tfdBienSoXe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdBienSoXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBienSoXeActionPerformed(evt);
            }
        });
        jPanel1.add(tfdBienSoXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 240, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 60, -1));

        tfdDiachiAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdDiachiAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDiachiAccountActionPerformed(evt);
            }
        });
        jPanel1.add(tfdDiachiAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 240, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Giới tính");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, -1));

        cbbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe máy", "Xe đạp" }));
        cbbLoaiXe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbbLoaiXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiXeItemStateChanged(evt);
            }
        });
        cbbLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiXeActionPerformed(evt);
            }
        });
        jPanel1.add(cbbLoaiXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 240, 30));

        labelBienSoXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBienSoXe.setText("Biển số xe");
        jPanel1.add(labelBienSoXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 90, -1));

        jdcNgaySinh.setDateFormatString("yyyy-MMM-dd");
        jPanel1.add(jdcNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 240, 30));

        btnHuyAccount.setBackground(new java.awt.Color(51, 51, 255));
        btnHuyAccount.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        btnHuyAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyAccount.setText("Hủy");
        btnHuyAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuyAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHuyAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuyAccountMouseExited(evt);
            }
        });
        btnHuyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuyAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 110, 40));

        btnCapNhatAccount.setBackground(new java.awt.Color(51, 51, 255));
        btnCapNhatAccount.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        btnCapNhatAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatAccount.setText("Cập nhật");
        btnCapNhatAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhatAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapNhatAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatAccountMouseExited(evt);
            }
        });
        btnCapNhatAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhatAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 110, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Số điện thoại");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 90, -1));

        tfdSDTAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdSDTAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdSDTAccountActionPerformed(evt);
            }
        });
        jPanel1.add(tfdSDTAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 240, 30));

        labelSoDu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSoDu.setText("Số dư");
        jPanel1.add(labelSoDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 90, -1));

        tfdSoDu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfdSoDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdSoDuActionPerformed(evt);
            }
        });
        jPanel1.add(tfdSoDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 240, 30));

        labelLoaiXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLoaiXe.setText("Loại xe");
        jPanel1.add(labelLoaiXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 90, -1));

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioiTinhActionPerformed(evt);
            }
        });
        jPanel1.add(cbbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatAccountActionPerformed

    private void tfdQueQuanAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdQueQuanAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdQueQuanAccountActionPerformed

    private void tfdHoTenAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdHoTenAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdHoTenAccountActionPerformed

    private void tfdEmailAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdEmailAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdEmailAccountActionPerformed

    private void tfdBienSoXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdBienSoXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdBienSoXeActionPerformed

    private void tfdDiachiAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDiachiAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDiachiAccountActionPerformed

    private void cbbLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiXeActionPerformed

    private void btnHomeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeAccountActionPerformed

    private void btnHuyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyAccountActionPerformed

    private void btnCapNhatAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatAccountActionPerformed

    private void btnCapNhatAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatAccountMouseEntered
        btnCapNhatAccount.setBackground(new Color(80, 60, 244));

    }//GEN-LAST:event_btnCapNhatAccountMouseEntered

    private void btnCapNhatAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatAccountMouseExited
        btnCapNhatAccount.setBackground(new Color(12, 33, 250));

    }//GEN-LAST:event_btnCapNhatAccountMouseExited

    private void btnHuyAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyAccountMouseEntered
        btnHuyAccount.setBackground(new Color(80, 60, 244));
    }//GEN-LAST:event_btnHuyAccountMouseEntered

    private void btnHuyAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyAccountMouseExited
        btnHuyAccount.setBackground(new Color(12, 33, 250));
    }//GEN-LAST:event_btnHuyAccountMouseExited

    private void btnThoatAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatAccountMouseClicked
        // TODO add your handling code here:
        DangNhap _login = new DangNhap();
        _login.show();
        dispose();
    }//GEN-LAST:event_btnThoatAccountMouseClicked

    //event click button home
    private void btnHomeAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeAccountMouseClicked
        // TODO add your handling code here:
        Homepage _homepage = null;
        try {
            _homepage = new Homepage();
        } catch (Exception ex) {
            Logger.getLogger(CapNhatThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
        }
        _homepage.show();
        dispose();
    }//GEN-LAST:event_btnHomeAccountMouseClicked

    //event click CapNhatAccount
    private void btnCapNhatAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatAccountMouseClicked
        // TODO add your handling code here:
        Calendar c1 = Calendar.getInstance();
        c1.set(Calendar.MONTH, 5);

        // set Date
        c1.set(Calendar.DATE, 26);

        // set Year
        c1.set(Calendar.YEAR, 2005);

        Date dateToday = c1.getTime();
        if (jdcNgaySinh.getDate().getTime() - dateToday.getTime() > 17 * 17 * 31536000) {
            JOptionPane.showMessageDialog(this, "Người dùng chưa đủ 17 tuổi");
            return;
        }
        
        try {
            if (Integer.parseInt(tfdSDTAccount.getText()) < 0) {
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ");
            return;
        }
        
        nd.setStrHoTen(tfdHoTenAccount.getText());
        nd.setStrEmail(tfdEmailAccount.getText());
        nd.setStrDiaChi(tfdDiachiAccount.getText());
        nd.setStrQueQuan(tfdQueQuanAccount.getText());
        nd.setStrSDT(tfdSDTAccount.getText());
        nd.setStrMatKhau("long2002");
        if (cbbGioiTinh.getSelectedItem().toString().equals("Nữ")) {
            nd.setStrGioiTinh("Nu");
        }
        if (cbbGioiTinh.getSelectedItem().toString().equals("Nam")) {
            nd.setStrGioiTinh("Nam");
        }
        txtHoTenAccount.setText(tfdHoTenAccount.getText());

        //Nếu là xe đạp hoặc xe máy có biển số thì thêm trường xe vào bảng XE
        if ((cbbLoaiXe.getSelectedItem().toString().equals("Xe đạp")
                || !tfdBienSoXe.getText().equals("")) && kh.getStrMaXe() == null) {
            XeDTO xe = new XeDTO();
            if (cbbLoaiXe.getSelectedItem().toString().equals("Xe đạp")) {
                xe.setStrTenLoaiXe("Xe dap");
            }
            if (cbbLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                xe.setStrTenLoaiXe("Xe may");
            }
            xe.setStrBienSoXe(tfdBienSoXe.getText());
            String maxMaXe = null;
            try {
                maxMaXe = xetbl.getMaxMaXe();
            } catch (Exception ex) {
                Logger.getLogger(CapNhatThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
            }

            xe.setStrMaXe(maxMaXe);
            try {
                xetbl.them(xe);
            } catch (Exception ex) {
                Logger.getLogger(CapNhatThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Cập nhật mã xe cho bảng khách hàng.
            kh.setStrMaXe(maxMaXe);
            try {
                khachhangtbl.sua(kh);
            } catch (Exception ex) {
                Logger.getLogger(CapNhatThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        //Nếu khách hàng đã có xe rồi
        if (kh.getStrMaXe() != null) {
            XeDTO xe = xetbl.getInfor(kh.getStrMaXe());
            if (cbbLoaiXe.getSelectedItem().toString().equals("Xe đạp")) {
                xe.setStrTenLoaiXe("Xe dap");
            }
            if (cbbLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                xe.setStrTenLoaiXe("Xe may");
            }
            xe.setStrBienSoXe(tfdBienSoXe.getText());
            try {
                xetbl.sua(xe);
            } catch (Exception ex) {
                Logger.getLogger(CapNhatThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jdcNgaySinh.getDate() != null) {
            nd.setDateNgSinh(jdcNgaySinh.getDate());
        }

        try {
            if (nd.getDateNgSinh() == null) {
                nguoidungtbl.suaKhongCoNgaySinh(nd);
            } else {
                nguoidungtbl.sua(nd);
            }
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            //Khi cập nhật thành công, giao diện sẽ trở về home
//            Homepage _homepage = new Homepage();
//            _homepage.show();
//            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
        }


    }//GEN-LAST:event_btnCapNhatAccountMouseClicked

    //event click button Huy Account
    private void btnHuyAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyAccountMouseClicked
        // TODO add your handling code here:
        /**
         * Khi click vào button hủy thì sẽ tự reset về các giá trị ban đầu trong
         * dtb tức là, nó sẽ render ra giao diện ban đầu Và setAccount() sẽ là
         * hàm đóng vai trò chức năng đó.
         */
        setAccount();
    }//GEN-LAST:event_btnHuyAccountMouseClicked

    private void tfdSDTAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdSDTAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdSDTAccountActionPerformed

    private void tfdSoDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdSoDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdSoDuActionPerformed

    private void cbbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGioiTinhActionPerformed

    //Nếu là xe đạp thì sẽ không cho nhập biển số
    private void cbbLoaiXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiXeItemStateChanged
        // TODO add your handling code here:
        if (cbbLoaiXe.getSelectedItem().toString().equals("Xe đạp")) {
            tfdBienSoXe.setText("");
            tfdBienSoXe.setEnabled(false);

        } else {
            tfdBienSoXe.setEnabled(true);
        }
    }//GEN-LAST:event_cbbLoaiXeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CapNhatThongTinKH().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CapNhatThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatAccount;
    private javax.swing.JButton btnHomeAccount;
    private javax.swing.JButton btnHuyAccount;
    private javax.swing.JButton btnThoatAccount;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<String> cbbLoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JLabel labelBienSoXe;
    private javax.swing.JLabel labelLoaiXe;
    private javax.swing.JLabel labelSoDu;
    private javax.swing.JTextField tfdBienSoXe;
    private javax.swing.JTextField tfdDiachiAccount;
    private javax.swing.JTextField tfdEmailAccount;
    private javax.swing.JTextField tfdHoTenAccount;
    private javax.swing.JTextField tfdQueQuanAccount;
    private javax.swing.JTextField tfdSDTAccount;
    private javax.swing.JTextField tfdSoDu;
    private javax.swing.JLabel txtHoTenAccount;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/parking.png")));

    }
}
