/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITParking.GUI;

import UITParking.BUS.CTHDMuaVeBUS;
import UITParking.BUS.HDMuaVeBUS;
import UITParking.BUS.KhachHangBUS;
import UITParking.BUS.VeBUS;
import UITParking.DTO.CTHDMuaVeDTO;
import UITParking.DTO.HDMuaVeDTO;
import UITParking.DTO.KhachHangDTO;
import UITParking.DTO.VeDTO;
import static UITParking.GUI.InitPublic.getDateThoiGianThuc;
import static UITParking.GUI.InitPublic.getThoiGianThuc;
import static UITParking.GUI.MuaVe.slVe3000Dong;
import static UITParking.GUI.MuaVe.slVe2000Dong;
import static UITParking.GUI.MuaVe.slVe25000Dong;
import static UITParking.GUI.MuaVe.slVe95000Dong;
import static UITParking.GUI.NapTien.tempTien;
import static UITParking.GUI.login.pMaND;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class GioHang extends javax.swing.JFrame {

    /**
     * Creates new form GioHang
     */
    public static int pTongTienThanhToan = 0;
    public static long tempTienGioHang = 0;
    KhachHangBUS khachhangtbl = new KhachHangBUS();
    KhachHangDTO kh = khachhangtbl.getInfor(pMaND);
    HDMuaVeBUS hdmuavetbl = new HDMuaVeBUS();
    CTHDMuaVeBUS cthdmuavetbl = new CTHDMuaVeBUS();
    VeBUS vetbl = new VeBUS();

    public GioHang() throws Exception {
        initComponents();

        KhachHangBUS khachhangtbl = new KhachHangBUS();
        KhachHangDTO kh = khachhangtbl.getInfor(pMaND);
        tempTienGioHang = kh.getLongSoDu();
        System.out.println("So tien" + tempTienGioHang);

        //Render giao diện giỏ hàng 
        renderGiaoDienGioHang();
        //Set số lượng ban đầu khi chọn mua vé
        setSLVeText();
        //Set tổng tiền dựa vào số lượng vé và đơn giá vé
        setTongTienThanhToan();

    }

    //Hàm render giao diện giỏ hàng dựa vào số lượng vé của từng loại
    public void renderGiaoDienGioHang() {
        if (slVe2000Dong <= 0 && slVe3000Dong <= 0
                && slVe25000Dong <= 0 && slVe95000Dong <= 0) {
//            empty.setVisible(true);
//            panelTitle.setVisible(false);
//            panelThanhToan.setVisible(false);

        } else {
//            empty.setVisible(false);
        }
        if (slVe2000Dong <= 0) {
            panelChiTietVe2000Dong.setVisible(false);
        }
        if (slVe3000Dong <= 0) {
            panelChiTietVe3000Dong.setVisible(false);
        }
        if (slVe25000Dong <= 0) {
            panelChiTietVe25000Dong.setVisible(false);
        }
        if (slVe95000Dong <= 0) {
            panelChiTietVe95000Dong.setVisible(false);
        }
    }

    //Hàm set số lượng ban đầu khi chọn mua vé
    public void setSLVeText() {
        txtSLVe2000Dong.setText(String.valueOf(slVe2000Dong));
        txtSLVe3000Dong.setText(String.valueOf(slVe3000Dong));
        txtSLVe25000Dong.setText(String.valueOf(slVe25000Dong));
        txtSLVe95000Dong.setText(String.valueOf(slVe95000Dong));
    }

    //Hàm set số lượng vé về 0.
    public void setSLVe0() {
        slVe2000Dong = 0;
        slVe25000Dong = 0;
        slVe3000Dong = 0;
        slVe95000Dong = 0;
    }

    //Hàm xóa các loại vé có trong giao diện
    public void xoaSLVe() {
        panelChiTietVe2000Dong.setVisible(false);
        panelChiTietVe25000Dong.setVisible(false);
        panelChiTietVe3000Dong.setVisible(false);
        panelChiTietVe95000Dong.setVisible(false);
    }

    //Hàm tính tổng tiền thanh toán
    public void setTongTienThanhToan() {
        pTongTienThanhToan = slVe2000Dong * 2000
                + slVe3000Dong * 3000
                + slVe25000Dong * 25000
                + slVe95000Dong * 95000;
        txtTongTienThanhToan.setText(String.valueOf(pTongTienThanhToan) + "đ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelChiTietVe3000Dong = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSLVe3000Dong = new javax.swing.JButton();
        btnTruSLVe3000Dong = new javax.swing.JButton();
        btnCongSLVe3000Dong = new javax.swing.JButton();
        btnXoaVe3000Dong = new javax.swing.JButton();
        panelThanhToan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTongTienThanhToan = new javax.swing.JLabel();
        btnThanhToanGioHang = new javax.swing.JButton();
        panelChiTietVe2000Dong = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSLVe2000Dong = new javax.swing.JButton();
        btnTruSLVe2000Dong = new javax.swing.JButton();
        btnCongSLVe2000Dong = new javax.swing.JButton();
        btnXoaVe2000Dong = new javax.swing.JButton();
        panelChiTietVe25000Dong = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSLVe25000Dong = new javax.swing.JButton();
        btnTruSLVe25000Dong = new javax.swing.JButton();
        btnCongSLVe25000Dong = new javax.swing.JButton();
        btnXoaVe25000Dong = new javax.swing.JButton();
        panelChiTietVe95000Dong = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSLVe95000Dong = new javax.swing.JButton();
        btnTruSLVe95000Dong = new javax.swing.JButton();
        btnCongSLVe95000Dong = new javax.swing.JButton();
        btnXoaVe95000Dong = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBackGioHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIỎ HÀNG");

        panelChiTietVe3000Dong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Vé Lượt Xe Máy");

        jLabel3.setText("Giá Đơn Vé: 3000đ");

        txtSLVe3000Dong.setText("SL Vé");

        btnTruSLVe3000Dong.setText("-");
        btnTruSLVe3000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTruSLVe3000DongMouseClicked(evt);
            }
        });

        btnCongSLVe3000Dong.setText("+");
        btnCongSLVe3000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongSLVe3000DongMouseClicked(evt);
            }
        });

        btnXoaVe3000Dong.setText("Xóa");
        btnXoaVe3000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaVe3000DongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChiTietVe3000DongLayout = new javax.swing.GroupLayout(panelChiTietVe3000Dong);
        panelChiTietVe3000Dong.setLayout(panelChiTietVe3000DongLayout);
        panelChiTietVe3000DongLayout.setHorizontalGroup(
            panelChiTietVe3000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe3000DongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelChiTietVe3000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChiTietVe3000DongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTruSLVe3000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLVe3000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCongSLVe3000Dong)
                .addGap(15, 15, 15)
                .addComponent(btnXoaVe3000Dong)
                .addContainerGap())
        );
        panelChiTietVe3000DongLayout.setVerticalGroup(
            panelChiTietVe3000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe3000DongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelChiTietVe3000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLVe3000Dong)
                    .addComponent(btnTruSLVe3000Dong)
                    .addComponent(btnCongSLVe3000Dong)
                    .addComponent(btnXoaVe3000Dong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Thành Tiền");

        txtTongTienThanhToan.setText("0 đ");

        btnThanhToanGioHang.setText("Thanh Toán");
        btnThanhToanGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanGioHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelThanhToanLayout = new javax.swing.GroupLayout(panelThanhToan);
        panelThanhToan.setLayout(panelThanhToanLayout);
        panelThanhToanLayout.setHorizontalGroup(
            panelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThanhToanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTongTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToanGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        panelThanhToanLayout.setVerticalGroup(
            panelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThanhToanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnThanhToanGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelChiTietVe2000Dong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Vé Lượt Xe Đạp");

        jLabel7.setText("Giá Đơn Vé: 2000đ");

        txtSLVe2000Dong.setText("SL Vé");

        btnTruSLVe2000Dong.setText("-");
        btnTruSLVe2000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTruSLVe2000DongMouseClicked(evt);
            }
        });

        btnCongSLVe2000Dong.setText("+");
        btnCongSLVe2000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongSLVe2000DongMouseClicked(evt);
            }
        });

        btnXoaVe2000Dong.setText("Xóa");
        btnXoaVe2000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaVe2000DongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChiTietVe2000DongLayout = new javax.swing.GroupLayout(panelChiTietVe2000Dong);
        panelChiTietVe2000Dong.setLayout(panelChiTietVe2000DongLayout);
        panelChiTietVe2000DongLayout.setHorizontalGroup(
            panelChiTietVe2000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe2000DongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelChiTietVe2000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChiTietVe2000DongLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(btnTruSLVe2000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLVe2000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCongSLVe2000Dong)
                .addGap(15, 15, 15)
                .addComponent(btnXoaVe2000Dong)
                .addContainerGap())
        );
        panelChiTietVe2000DongLayout.setVerticalGroup(
            panelChiTietVe2000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe2000DongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelChiTietVe2000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLVe2000Dong)
                    .addComponent(btnTruSLVe2000Dong)
                    .addComponent(btnCongSLVe2000Dong)
                    .addComponent(btnXoaVe2000Dong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelChiTietVe25000Dong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Vé Tuần");

        jLabel9.setText("Giá Đơn Vé: 25000đ");

        txtSLVe25000Dong.setText("SL Vé");

        btnTruSLVe25000Dong.setText("-");
        btnTruSLVe25000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTruSLVe25000DongMouseClicked(evt);
            }
        });

        btnCongSLVe25000Dong.setText("+");
        btnCongSLVe25000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongSLVe25000DongMouseClicked(evt);
            }
        });

        btnXoaVe25000Dong.setText("Xóa");
        btnXoaVe25000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaVe25000DongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChiTietVe25000DongLayout = new javax.swing.GroupLayout(panelChiTietVe25000Dong);
        panelChiTietVe25000Dong.setLayout(panelChiTietVe25000DongLayout);
        panelChiTietVe25000DongLayout.setHorizontalGroup(
            panelChiTietVe25000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe25000DongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelChiTietVe25000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChiTietVe25000DongLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(btnTruSLVe25000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLVe25000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCongSLVe25000Dong)
                .addGap(15, 15, 15)
                .addComponent(btnXoaVe25000Dong)
                .addContainerGap())
        );
        panelChiTietVe25000DongLayout.setVerticalGroup(
            panelChiTietVe25000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe25000DongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelChiTietVe25000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLVe25000Dong)
                    .addComponent(btnTruSLVe25000Dong)
                    .addComponent(btnCongSLVe25000Dong)
                    .addComponent(btnXoaVe25000Dong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelChiTietVe95000Dong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Vé Tháng");

        jLabel11.setText("Giá Đơn Vé: 95000đ");

        txtSLVe95000Dong.setText("SL Vé");

        btnTruSLVe95000Dong.setText("-");
        btnTruSLVe95000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTruSLVe95000DongMouseClicked(evt);
            }
        });

        btnCongSLVe95000Dong.setText("+");
        btnCongSLVe95000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongSLVe95000DongMouseClicked(evt);
            }
        });

        btnXoaVe95000Dong.setText("Xóa");
        btnXoaVe95000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaVe95000DongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChiTietVe95000DongLayout = new javax.swing.GroupLayout(panelChiTietVe95000Dong);
        panelChiTietVe95000Dong.setLayout(panelChiTietVe95000DongLayout);
        panelChiTietVe95000DongLayout.setHorizontalGroup(
            panelChiTietVe95000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe95000DongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelChiTietVe95000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChiTietVe95000DongLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(btnTruSLVe95000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLVe95000Dong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCongSLVe95000Dong)
                .addGap(15, 15, 15)
                .addComponent(btnXoaVe95000Dong)
                .addContainerGap())
        );
        panelChiTietVe95000DongLayout.setVerticalGroup(
            panelChiTietVe95000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietVe95000DongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelChiTietVe95000DongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLVe95000Dong)
                    .addComponent(btnTruSLVe95000Dong)
                    .addComponent(btnCongSLVe95000Dong)
                    .addComponent(btnXoaVe95000Dong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Tên Vé");

        jLabel13.setText("Số Lượng Vé");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnBackGioHang.setText("Back");
        btnBackGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackGioHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelChiTietVe95000Dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelChiTietVe25000Dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelChiTietVe2000Dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelChiTietVe3000Dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addComponent(panelThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(btnBackGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChiTietVe3000Dong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelChiTietVe2000Dong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panelChiTietVe25000Dong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelChiTietVe95000Dong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Event click button back ở trang giỏ hàng.
    private void btnBackGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackGioHangMouseClicked
        // TODO add your handling code here:
        MuaVe _muaVe = new MuaVe();
        _muaVe.show();
        dispose();
    }//GEN-LAST:event_btnBackGioHangMouseClicked

    //Evenet click button cộng số lượng vé cho vé 3000 đồng
    private void btnCongSLVe3000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongSLVe3000DongMouseClicked
        // TODO add your handling code here:
        slVe3000Dong = slVe3000Dong + 1;
        txtSLVe3000Dong.setText(String.valueOf(slVe3000Dong));
        setTongTienThanhToan();
    }//GEN-LAST:event_btnCongSLVe3000DongMouseClicked

    //Evenet click button trừ số lượng vé cho vé 3000 đồng
    //Nếu số lượng vé là 1 thì phương thức này sẽ không được thực hiện
    private void btnTruSLVe3000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTruSLVe3000DongMouseClicked
        // TODO add your handling code here:
        if (slVe3000Dong > 1) {
            slVe3000Dong = slVe3000Dong - 1;
            txtSLVe3000Dong.setText(String.valueOf(slVe3000Dong));
            setTongTienThanhToan();
        }
    }//GEN-LAST:event_btnTruSLVe3000DongMouseClicked

    //Event click button xóa loại vé 3000 đồng ra khỏi giỏ hàng
    private void btnXoaVe3000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaVe3000DongMouseClicked
        // TODO add your handling code here:
        panelChiTietVe3000Dong.setVisible(false);
        slVe3000Dong = 0;
        setTongTienThanhToan();
    }//GEN-LAST:event_btnXoaVe3000DongMouseClicked

    //Evenet click button cộng số lượng vé cho vé 2000 đồng
    private void btnCongSLVe2000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongSLVe2000DongMouseClicked
        // TODO add your handling code here:
        slVe2000Dong = slVe2000Dong + 1;
        txtSLVe2000Dong.setText(String.valueOf(slVe2000Dong));
        setTongTienThanhToan();
    }//GEN-LAST:event_btnCongSLVe2000DongMouseClicked

    //Evenet click button trừ số lượng vé cho vé 2000 đồng
    //Nếu số lượng vé là 1 thì phương thức này sẽ không được thực hiện
    private void btnTruSLVe2000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTruSLVe2000DongMouseClicked
        if (slVe2000Dong > 1) {
            slVe2000Dong = slVe2000Dong - 1;
            txtSLVe2000Dong.setText(String.valueOf(slVe2000Dong));
            setTongTienThanhToan();
        }
    }//GEN-LAST:event_btnTruSLVe2000DongMouseClicked

    //Event click button xóa loại vé 2000 đồng ra khỏi giỏ hàng
    private void btnXoaVe2000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaVe2000DongMouseClicked
        // TODO add your handling code here:
        panelChiTietVe2000Dong.setVisible(false);
        slVe2000Dong = 0;
        setTongTienThanhToan();
    }//GEN-LAST:event_btnXoaVe2000DongMouseClicked

    //Evenet click button cộng số lượng vé cho vé 25000 đồng
    private void btnCongSLVe25000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongSLVe25000DongMouseClicked
        // TODO add your handling code here:
        slVe25000Dong = slVe25000Dong + 1;
        txtSLVe25000Dong.setText(String.valueOf(slVe25000Dong));
        setTongTienThanhToan();
    }//GEN-LAST:event_btnCongSLVe25000DongMouseClicked

    //Evenet click button trừ số lượng vé cho vé 25000 đồng
    //Nếu số lượng vé là 1 thì phương thức này sẽ không được thực hiện
    private void btnTruSLVe25000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTruSLVe25000DongMouseClicked
        // TODO add your handling code here:
        if (slVe25000Dong > 1) {
            slVe25000Dong = slVe25000Dong - 1;
            txtSLVe25000Dong.setText(String.valueOf(slVe25000Dong));
            setTongTienThanhToan();
        }
    }//GEN-LAST:event_btnTruSLVe25000DongMouseClicked

    //Event click button xóa loại vé 25000 đồng ra khỏi giỏ hàng
    private void btnXoaVe25000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaVe25000DongMouseClicked
        // TODO add your handling code here:
        panelChiTietVe25000Dong.setVisible(false);
        slVe25000Dong = 0;
        setTongTienThanhToan();
    }//GEN-LAST:event_btnXoaVe25000DongMouseClicked

    //Evenet click button cộng số lượng vé cho vé 95000 đồng
    private void btnCongSLVe95000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongSLVe95000DongMouseClicked
        // TODO add your handling code here:
        slVe95000Dong = slVe95000Dong + 1;
        txtSLVe95000Dong.setText(String.valueOf(slVe95000Dong));
        setTongTienThanhToan();
    }//GEN-LAST:event_btnCongSLVe95000DongMouseClicked

    //Evenet click button trừ số lượng vé cho vé 95000 đồng
    //Nếu số lượng vé là 1 thì phương thức này sẽ không được thực hiện
    private void btnTruSLVe95000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTruSLVe95000DongMouseClicked
        // TODO add your handling code here:
        if (slVe95000Dong > 1) {
            slVe95000Dong = slVe95000Dong - 1;
            txtSLVe95000Dong.setText(String.valueOf(slVe95000Dong));
            setTongTienThanhToan();
        }
    }//GEN-LAST:event_btnTruSLVe95000DongMouseClicked

    //Event click button xóa loại vé 95000 đồng ra khỏi giỏ hàng
    private void btnXoaVe95000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaVe95000DongMouseClicked
        // TODO add your handling code here:
        panelChiTietVe95000Dong.setVisible(false);
        slVe95000Dong = 0;
        setTongTienThanhToan();
    }//GEN-LAST:event_btnXoaVe95000DongMouseClicked

    //Event click button thanh toán giỏ hàng
    private void btnThanhToanGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanGioHangMouseClicked
        // TODO add your handling code here:
        System.out.println("Tong tien thanh toan: " + pTongTienThanhToan);
        System.out.println("Tong tien trong vi nguoi dung: " + tempTienGioHang);
        //Nếu tiền thanh toán bé hơn hoặc bằng số tiền mà người dùng có thì cho phép thanh toán
        if (pTongTienThanhToan <= tempTienGioHang) {

            tempTienGioHang = tempTienGioHang - pTongTienThanhToan;

//            System.out.println("Tong tien thanh toan con lai: " + pTongTienThanhToan);
//            System.out.println("Temp Tien Gio Hang con lai: " + tempTienGioHang);
//            System.out.println("Thanh toan thanh cong");
            kh.setLongSoDu(tempTienGioHang);
            try {
                //Cập nhật dữ liệu
                khachhangtbl.sua(kh);
                //Hiện ra thông báo thanh toán thành công.
                JOptionPane.showMessageDialog(null, "Thanh toán thành công, "
                        + "số dư còn lại của bạn là: " + kh.getLongSoDu() + "đ");

                /*
                 * Tạo hóa đơn mới cho dữ liệu vừa được thêm vào
                 * Hóa đơn thêm vào gồm các trường Mã hóa đơn, tăng tự động, 
                  Mã khách hàng, ngày hóa đơn(Ngày hiện tại, sysdate) tổng trị giá của hóa đơn
                 * 
                 */
                System.out.println("Tổng số tiền cần thanh toán " + pTongTienThanhToan);
                System.out.println("Số lượng vé của LVE01 - Vé lượt xe máy - 3000đ là: " + slVe3000Dong);
                System.out.println("Số lượng vé của LVE02 - Vé lượt xe đạp - 2000đ là: " + slVe2000Dong);
                System.out.println("Số lượng vé của LVE03 - Vé tuần - 25000đ là: " + slVe25000Dong);
                System.out.println("Số lượng vé của LVE01 - Vé tháng - 95000đ là: " + slVe95000Dong);
                System.out.println("Mã khách hàng hiện tại là: " + kh.getStrMaKH());

                //Tạo mã hóa đơn mới cho bảng HOADONMUAVE
                //Lấy ra người dùng có mã max để từ đó chèn người tiếp theo vào
                String maHD = hdmuavetbl.getMaxMaHD();
                HDMuaVeDTO hd = new HDMuaVeDTO(maHD, kh.getStrMaKH(), getDateThoiGianThuc(), pTongTienThanhToan);
                hdmuavetbl.them(hd);

                /**
                 * Tạo CTHD mới Nếu số lượng của loại vé > 0 thì tạo CTHD mới
                 */
                if (slVe2000Dong > 0) {
                    CTHDMuaVeDTO cthd = new CTHDMuaVeDTO(maHD, "LVE02", slVe2000Dong);
                    cthdmuavetbl.them(cthd);
                    for(int i = 0; i < slVe2000Dong; i++){
                        String maVe = vetbl.getMaxMaVe();
                        VeDTO ve = new VeDTO(maVe, "LVE02", kh.getStrMaKH(), "", "", "Chưa kích hoạt");
                        vetbl.them(ve);
                    }
                }
                if (slVe3000Dong > 0) {
                    CTHDMuaVeDTO cthd = new CTHDMuaVeDTO(maHD, "LVE01", slVe3000Dong);
                    cthdmuavetbl.them(cthd);
                    for(int i = 0; i < slVe3000Dong; i++){
                        String maVe = vetbl.getMaxMaVe();
                        VeDTO ve = new VeDTO(maVe, "LVE01", kh.getStrMaKH(), "", "", "Chưa kích hoạt");
                        vetbl.them(ve);
                    }
                }
                if (slVe25000Dong > 0) {
                    CTHDMuaVeDTO cthd = new CTHDMuaVeDTO(maHD, "LVE03", slVe25000Dong);
                    cthdmuavetbl.them(cthd);
                    for(int i = 0; i < slVe25000Dong; i++){
                        String maVe = vetbl.getMaxMaVe();
                        VeDTO ve = new VeDTO(maVe, "LVE03", kh.getStrMaKH(), "", "", "Chưa kích hoạt");
                        vetbl.them(ve);
                    }
                }
                if (slVe95000Dong > 0) {
                    CTHDMuaVeDTO cthd = new CTHDMuaVeDTO(maHD, "LVE04", slVe95000Dong);
                    cthdmuavetbl.them(cthd);
                    for(int i = 0; i < slVe95000Dong; i++){
                        String maVe = vetbl.getMaxMaVe();
                        VeDTO ve = new VeDTO(maVe, "LVE04", kh.getStrMaKH(), "", "", "Chưa kích hoạt");
                        vetbl.them(ve);
                    }
                }

                /**
                 * Cập nhật tổng tiền về 0 Cập nhật số lượng vé, xóa các loại vé
                 * còn trong giỏ hàng
                 */
                //Cập nhật lại tổng tiền thanh toán về 0.
                pTongTienThanhToan = 0;
                txtTongTienThanhToan.setText(String.valueOf(pTongTienThanhToan) + "đ");
                //Xóa các loại vé trong giỏ hàng.
                xoaSLVe();
                //Set số lượng các loại vé về 0
                setSLVe0();

            } catch (Exception ex) {
                Logger.getLogger(GioHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {//Ngược lại thì thông báo cho người dùng việc thanh toán thất bại.
            JOptionPane.showMessageDialog(null, "Số dư của khách hàng là: " + kh.getLongSoDu()
                    + "đ, không đủ để thanh toán. Vui lòng nạp tiền thêm!!!");
        }

    }//GEN-LAST:event_btnThanhToanGioHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GioHang().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(GioHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackGioHang;
    private javax.swing.JButton btnCongSLVe2000Dong;
    private javax.swing.JButton btnCongSLVe25000Dong;
    private javax.swing.JButton btnCongSLVe3000Dong;
    private javax.swing.JButton btnCongSLVe95000Dong;
    private javax.swing.JButton btnThanhToanGioHang;
    private javax.swing.JButton btnTruSLVe2000Dong;
    private javax.swing.JButton btnTruSLVe25000Dong;
    private javax.swing.JButton btnTruSLVe3000Dong;
    private javax.swing.JButton btnTruSLVe95000Dong;
    private javax.swing.JButton btnXoaVe2000Dong;
    private javax.swing.JButton btnXoaVe25000Dong;
    private javax.swing.JButton btnXoaVe3000Dong;
    private javax.swing.JButton btnXoaVe95000Dong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelChiTietVe2000Dong;
    private javax.swing.JPanel panelChiTietVe25000Dong;
    private javax.swing.JPanel panelChiTietVe3000Dong;
    private javax.swing.JPanel panelChiTietVe95000Dong;
    private javax.swing.JPanel panelThanhToan;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton txtSLVe2000Dong;
    private javax.swing.JButton txtSLVe25000Dong;
    private javax.swing.JButton txtSLVe3000Dong;
    private javax.swing.JButton txtSLVe95000Dong;
    private javax.swing.JLabel txtTongTienThanhToan;
    // End of variables declaration//GEN-END:variables
}
