/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITParking.GUI;

import UITParking.BUS.NguoiDungBUS;
import UITParking.DTO.NguoiDungDTO;
import static UITParking.GUI.login.pMaND;
import UITParking.TEST2.MainForm;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pham Hoang Ngoc Anh
 */
public class HomepageAdmin extends javax.swing.JFrame {

    public static String kindSelectedPublic = "";

    /**
     * Creates new form HomepageAdmin
     */
    public HomepageAdmin() throws Exception {
        NguoiDungBUS nguoidungtbl = new NguoiDungBUS();
        NguoiDungDTO nd = nguoidungtbl.getInfor(pMaND);
        initComponents();
        setIconImage();
        txtNhanVienId.setText(nd.getStrMaND());
        txtHoTenNhanVien.setText(nd.getStrHoTen());
        txtChucVuNhanVien.setText(nd.getStrVaiTro());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelAdminQLKH = new Admin.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        label_QLKH = new javax.swing.JLabel();
        panelAdminQLV = new Admin.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        label_QLVE = new javax.swing.JLabel();
        panelAdminQLNV = new Admin.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        label_QLNV = new javax.swing.JLabel();
        panelAdminQLHD = new Admin.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        label_QLHD = new javax.swing.JLabel();
        panelAdminQLDT = new Admin.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        label_QLDT = new javax.swing.JLabel();
        panelAdminBCTK = new Admin.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        label_BCTK = new javax.swing.JLabel();
        panelRound1 = new Admin.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNhanVienId = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtChucVuNhanVien = new javax.swing.JLabel();
        txtHoTenNhanVien = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_DangXuat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelAdminQLKVL = new Admin.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        label_QLKVL = new javax.swing.JLabel();
        panelAdminQLX = new Admin.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        label_QLXE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UIT Parking");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdminQLKH.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLKH.setRoundBottomLeft(50);
        panelAdminQLKH.setRoundBottomRight(50);
        panelAdminQLKH.setRoundTopLeft(50);
        panelAdminQLKH.setRoundTopRight(50);
        panelAdminQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLKHMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/qlkh.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLKH.setBackground(new java.awt.Color(51, 51, 51));
        label_QLKH.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLKH.setForeground(new java.awt.Color(0, 0, 102));
        label_QLKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLKH.setText("Quản lý khách hàng");
        label_QLKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_QLKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLKHMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLKHLayout = new javax.swing.GroupLayout(panelAdminQLKH);
        panelAdminQLKH.setLayout(panelAdminQLKHLayout);
        panelAdminQLKHLayout.setHorizontalGroup(
            panelAdminQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_QLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAdminQLKHLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAdminQLKHLayout.setVerticalGroup(
            panelAdminQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLKHLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_QLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 200));

        panelAdminQLV.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLV.setRoundBottomLeft(50);
        panelAdminQLV.setRoundBottomRight(50);
        panelAdminQLV.setRoundTopLeft(50);
        panelAdminQLV.setRoundTopRight(50);
        panelAdminQLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLVMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vé.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLVE.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLVE.setForeground(new java.awt.Color(0, 0, 102));
        label_QLVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLVE.setText("Quản lý vé");
        label_QLVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_QLVEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLVEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLVEMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLVLayout = new javax.swing.GroupLayout(panelAdminQLV);
        panelAdminQLV.setLayout(panelAdminQLVLayout);
        panelAdminQLVLayout.setHorizontalGroup(
            panelAdminQLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_QLVE, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelAdminQLVLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAdminQLVLayout.setVerticalGroup(
            panelAdminQLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLVLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_QLVE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 180, 200));

        panelAdminQLNV.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLNV.setRoundBottomLeft(50);
        panelAdminQLNV.setRoundBottomRight(50);
        panelAdminQLNV.setRoundTopLeft(50);
        panelAdminQLNV.setRoundTopRight(50);
        panelAdminQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLNVMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ttstaff.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLNV.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLNV.setForeground(new java.awt.Color(0, 0, 102));
        label_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLNV.setText("Quản lý nhân viên");
        label_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_QLNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLNVMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLNVLayout = new javax.swing.GroupLayout(panelAdminQLNV);
        panelAdminQLNV.setLayout(panelAdminQLNVLayout);
        panelAdminQLNVLayout.setHorizontalGroup(
            panelAdminQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminQLNVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelAdminQLNVLayout.setVerticalGroup(
            panelAdminQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLNVLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 180, 200));

        panelAdminQLHD.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLHD.setRoundBottomLeft(50);
        panelAdminQLHD.setRoundBottomRight(50);
        panelAdminQLHD.setRoundTopLeft(50);
        panelAdminQLHD.setRoundTopRight(50);
        panelAdminQLHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLHDMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLHD.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLHD.setForeground(new java.awt.Color(0, 0, 102));
        label_QLHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLHD.setText("Quản lý hóa đơn");
        label_QLHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_QLHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLHDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLHDLayout = new javax.swing.GroupLayout(panelAdminQLHD);
        panelAdminQLHD.setLayout(panelAdminQLHDLayout);
        panelAdminQLHDLayout.setHorizontalGroup(
            panelAdminQLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminQLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_QLHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAdminQLHDLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAdminQLHDLayout.setVerticalGroup(
            panelAdminQLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLHDLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 180, 200));

        panelAdminQLDT.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLDT.setRoundBottomLeft(50);
        panelAdminQLDT.setRoundBottomRight(50);
        panelAdminQLDT.setRoundTopLeft(50);
        panelAdminQLDT.setRoundTopRight(50);
        panelAdminQLDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLDTMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doanhthu.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLDT.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLDT.setForeground(new java.awt.Color(0, 0, 102));
        label_QLDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLDT.setText("Quản lý doanh thu");
        label_QLDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLDTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLDTLayout = new javax.swing.GroupLayout(panelAdminQLDT);
        panelAdminQLDT.setLayout(panelAdminQLDTLayout);
        panelAdminQLDTLayout.setHorizontalGroup(
            panelAdminQLDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLDTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminQLDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_QLDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAdminQLDTLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAdminQLDTLayout.setVerticalGroup(
            panelAdminQLDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLDTLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_QLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 180, 200));

        panelAdminBCTK.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminBCTK.setRoundBottomLeft(50);
        panelAdminBCTK.setRoundBottomRight(50);
        panelAdminBCTK.setRoundTopLeft(50);
        panelAdminBCTK.setRoundTopRight(50);
        panelAdminBCTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminBCTKMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/báo cáo.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_BCTK.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_BCTK.setForeground(new java.awt.Color(0, 0, 102));
        label_BCTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_BCTK.setText("Báo cáo & Thống kê");
        label_BCTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_BCTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_BCTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_BCTKMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminBCTKLayout = new javax.swing.GroupLayout(panelAdminBCTK);
        panelAdminBCTK.setLayout(panelAdminBCTKLayout);
        panelAdminBCTKLayout.setHorizontalGroup(
            panelAdminBCTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminBCTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_BCTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelAdminBCTKLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelAdminBCTKLayout.setVerticalGroup(
            panelAdminBCTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminBCTKLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_BCTK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminBCTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 180, 200));

        panelRound1.setBackground(new java.awt.Color(249, 249, 249));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/boss.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("ID:");

        txtNhanVienId.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        txtNhanVienId.setForeground(new java.awt.Color(0, 0, 102));
        txtNhanVienId.setText("Quản trị viên");

        jLabel9.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Chức vụ:");

        txtChucVuNhanVien.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        txtChucVuNhanVien.setForeground(new java.awt.Color(0, 0, 102));
        txtChucVuNhanVien.setText("Quản trị viên");

        txtHoTenNhanVien.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        txtHoTenNhanVien.setForeground(new java.awt.Color(0, 0, 102));
        txtHoTenNhanVien.setText("Quản trị viên");

        jLabel14.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Họ tên: ");

        label_DangXuat.setFont(new java.awt.Font("Cooper", 0, 20)); // NOI18N
        label_DangXuat.setForeground(new java.awt.Color(0, 0, 102));
        label_DangXuat.setText("Đăng xuất");
        label_DangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_DangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_DangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_DangXuatMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNhanVienId)
                    .addComponent(txtHoTenNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(txtChucVuNhanVien))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(label_DangXuat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)))
                .addGap(149, 149, 149))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNhanVienId)
                            .addComponent(txtChucVuNhanVien)
                            .addComponent(jLabel9))
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtHoTenNhanVien)
                                    .addComponent(label_DangXuat)))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 980, 80));

        panelAdminQLKVL.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLKVL.setRoundBottomLeft(50);
        panelAdminQLKVL.setRoundBottomRight(50);
        panelAdminQLKVL.setRoundTopLeft(50);
        panelAdminQLKVL.setRoundTopRight(50);
        panelAdminQLKVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLKVLMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imgonline-com-ua-resize-CzYCHQERVknJOb.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLKVL.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLKVL.setForeground(new java.awt.Color(0, 0, 102));
        label_QLKVL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLKVL.setText("Quản lý khách vãng lai");
        label_QLKVL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLKVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_QLKVLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLKVLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLKVLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLKVLLayout = new javax.swing.GroupLayout(panelAdminQLKVL);
        panelAdminQLKVL.setLayout(panelAdminQLKVLLayout);
        panelAdminQLKVLLayout.setHorizontalGroup(
            panelAdminQLKVLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLKVLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_QLKVL, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelAdminQLKVLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAdminQLKVLLayout.setVerticalGroup(
            panelAdminQLKVLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLKVLLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_QLKVL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLKVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 190, 200));

        panelAdminQLX.setBackground(new java.awt.Color(255, 255, 255));
        panelAdminQLX.setRoundBottomLeft(50);
        panelAdminQLX.setRoundBottomRight(50);
        panelAdminQLX.setRoundTopLeft(50);
        panelAdminQLX.setRoundTopRight(50);
        panelAdminQLX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminQLXMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xe.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_QLXE.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        label_QLXE.setForeground(new java.awt.Color(0, 0, 102));
        label_QLXE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_QLXE.setText("Quản lý xe");
        label_QLXE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_QLXE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_QLXEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_QLXEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_QLXEMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAdminQLXLayout = new javax.swing.GroupLayout(panelAdminQLX);
        panelAdminQLX.setLayout(panelAdminQLXLayout);
        panelAdminQLXLayout.setHorizontalGroup(
            panelAdminQLXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_QLXE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelAdminQLXLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelAdminQLXLayout.setVerticalGroup(
            panelAdminQLXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminQLXLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_QLXE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdminQLX, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 190, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/wepik--202255-22401.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_QLKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLKHMouseEntered
        // TODO add your handling code here:

        label_QLKH.setForeground(new Color(191, 207, 255));
    }//GEN-LAST:event_label_QLKHMouseEntered

    private void label_QLKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLKHMouseExited
        // TODO add your handling code here:
        label_QLKH.setForeground(new Color(0, 0, 102));

    }//GEN-LAST:event_label_QLKHMouseExited

    private void label_QLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLNVMouseEntered
        label_QLNV.setForeground(new Color(191, 207, 255));

    }//GEN-LAST:event_label_QLNVMouseEntered

    private void label_QLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLNVMouseExited
        label_QLNV.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_QLNVMouseExited

    private void label_QLVEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLVEMouseEntered
        label_QLVE.setForeground(new Color(191, 207, 255));

    }//GEN-LAST:event_label_QLVEMouseEntered

    private void label_QLVEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLVEMouseExited
        label_QLVE.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_QLVEMouseExited

    private void label_QLHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLHDMouseEntered
        label_QLHD.setForeground(new Color(191, 207, 255));

    }//GEN-LAST:event_label_QLHDMouseEntered

    private void label_QLHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLHDMouseExited
        label_QLHD.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_QLHDMouseExited

    private void label_QLDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLDTMouseEntered
        label_QLDT.setForeground(new Color(191, 207, 255));
    }//GEN-LAST:event_label_QLDTMouseEntered

    private void label_QLDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLDTMouseExited
        label_QLDT.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_QLDTMouseExited

    private void label_BCTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_BCTKMouseEntered
        label_BCTK.setForeground(new Color(191, 207, 255));
    }//GEN-LAST:event_label_BCTKMouseEntered

    private void label_BCTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_BCTKMouseExited
        label_BCTK.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_BCTKMouseExited

    private void label_QLKVLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLKVLMouseEntered
        label_QLKVL.setForeground(new Color(191, 207, 255));

    }//GEN-LAST:event_label_QLKVLMouseEntered

    private void label_QLKVLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLKVLMouseExited
        label_QLKVL.setForeground(new Color(0, 0, 102));

    }//GEN-LAST:event_label_QLKVLMouseExited

    private void label_QLXEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLXEMouseEntered
        label_QLXE.setForeground(new Color(191, 207, 255));

    }//GEN-LAST:event_label_QLXEMouseEntered

    private void label_QLXEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLXEMouseExited
        label_QLXE.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_QLXEMouseExited

    private void label_DangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_DangXuatMouseEntered
        label_DangXuat.setForeground(new Color(191, 207, 255));

    }//GEN-LAST:event_label_DangXuatMouseEntered

    private void label_DangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_DangXuatMouseExited
        label_DangXuat.setForeground(new Color(0, 0, 102));
    }//GEN-LAST:event_label_DangXuatMouseExited

    private void panelAdminQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLKHMouseClicked
        // TODO add your handling code here:
        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
            kindSelectedPublic = "QLKH";
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_panelAdminQLKHMouseClicked

    private void label_QLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLKHMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLKH";
        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_label_QLKHMouseClicked

    private void panelAdminQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLNVMouseClicked
        kindSelectedPublic = "QLNV";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_panelAdminQLNVMouseClicked

    private void panelAdminQLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLVMouseClicked
        kindSelectedPublic = "QLV";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_panelAdminQLVMouseClicked

    private void panelAdminQLKVLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLKVLMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLKVL";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_panelAdminQLKVLMouseClicked

    private void panelAdminQLHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLHDMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLHD";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_panelAdminQLHDMouseClicked

    private void panelAdminQLDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLDTMouseClicked
        // TODO add your handling code here:            
//        kindSelectedPublic = "QLDT";
//
//        MainForm _mainForm = null;
//        try {
//            _mainForm = new MainForm();
//        } catch (Exception ex) {
//            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        _mainForm.show();
//        dispose();
    }//GEN-LAST:event_panelAdminQLDTMouseClicked

    private void panelAdminBCTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminBCTKMouseClicked
        // TODO add your handling code here:
//        kindSelectedPublic = "BCTK";
//        MainForm _mainForm = null;
//        try {
//            _mainForm = new MainForm();
//
//        } catch (Exception ex) {
//            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        _mainForm.show();
//        dispose();
    }//GEN-LAST:event_panelAdminBCTKMouseClicked

    private void panelAdminQLXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminQLXMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLX";
        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();

        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_panelAdminQLXMouseClicked

    private void label_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_DangXuatMouseClicked
        // TODO add your handling code here:
        login _login = new login();
        _login.show();
        dispose();
    }//GEN-LAST:event_label_DangXuatMouseClicked

    private void label_QLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLNVMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLNV";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_label_QLNVMouseClicked

    private void label_QLVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLVEMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLV";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_label_QLVEMouseClicked

    private void label_QLKVLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLKVLMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLKVL";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_label_QLKVLMouseClicked

    private void label_QLHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLHDMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLHD";

        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();
        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_label_QLHDMouseClicked

    private void label_QLXEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_QLXEMouseClicked
        // TODO add your handling code here:
        kindSelectedPublic = "QLX";
        MainForm _mainForm = null;
        try {
            _mainForm = new MainForm();

        } catch (Exception ex) {
            Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        _mainForm.show();
        dispose();
    }//GEN-LAST:event_label_QLXEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomepageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomepageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomepageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomepageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomepageAdmin().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(HomepageAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_BCTK;
    private javax.swing.JLabel label_DangXuat;
    private javax.swing.JLabel label_QLDT;
    private javax.swing.JLabel label_QLHD;
    private javax.swing.JLabel label_QLKH;
    private javax.swing.JLabel label_QLKVL;
    private javax.swing.JLabel label_QLNV;
    private javax.swing.JLabel label_QLVE;
    private javax.swing.JLabel label_QLXE;
    private Admin.PanelRound panelAdminBCTK;
    private Admin.PanelRound panelAdminQLDT;
    private Admin.PanelRound panelAdminQLHD;
    private Admin.PanelRound panelAdminQLKH;
    private Admin.PanelRound panelAdminQLKVL;
    private Admin.PanelRound panelAdminQLNV;
    private Admin.PanelRound panelAdminQLV;
    private Admin.PanelRound panelAdminQLX;
    private Admin.PanelRound panelRound1;
    private javax.swing.JLabel txtChucVuNhanVien;
    private javax.swing.JLabel txtHoTenNhanVien;
    private javax.swing.JLabel txtNhanVienId;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/parking.png")));

    }
}
