/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITParking.GUI;

import UITParking.BUS.KhachHangBUS;
import UITParking.DTO.KhachHangDTO;
import static UITParking.GUI.DangNhap.pMaND;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pham Hoang Ngoc Anh
 */
public class NapTien extends javax.swing.JFrame {

    /**
     * Creates new form NapTien
     */
    public static long tempTien;
    KhachHangBUS khachhangtbl = new KhachHangBUS();
    KhachHangDTO kh = khachhangtbl.getInfor(pMaND);

    public NapTien() throws Exception {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfldNapTien = new javax.swing.JTextField();
        btnNapTien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn100000Dong = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        btn10000Dong = new javax.swing.JToggleButton();
        btn20000Dong = new javax.swing.JToggleButton();
        btn50000Dong = new javax.swing.JToggleButton();
        btnBackNapTien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UIT Parking");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        jLabel1.setText("Số tiền cần nạp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 30));

        txtfldNapTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldNapTienActionPerformed(evt);
            }
        });
        jPanel1.add(txtfldNapTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 34));

        btnNapTien.setBackground(new java.awt.Color(255, 204, 51));
        btnNapTien.setFont(new java.awt.Font("Cooper", 0, 18)); // NOI18N
        btnNapTien.setText("Nạp tiền");
        btnNapTien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNapTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNapTienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNapTienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNapTienMouseExited(evt);
            }
        });
        btnNapTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapTienActionPerformed(evt);
            }
        });
        jPanel1.add(btnNapTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 220, 41));

        jPanel2.setBackground(new java.awt.Color(41, 58, 128));

        jLabel2.setFont(new java.awt.Font("Cooper", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 148, 34));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nạp tiền vào ví");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn100000Dong.setText("100.000đ");
        btn100000Dong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn100000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn100000DongMouseClicked(evt);
            }
        });
        btn100000Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100000DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn100000Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/wallet.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, -1));

        btn10000Dong.setText("10.000đ");
        btn10000Dong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn10000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10000DongMouseClicked(evt);
            }
        });
        btn10000Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn10000Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, -1));

        btn20000Dong.setText("20.000đ");
        btn20000Dong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn20000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn20000DongMouseClicked(evt);
            }
        });
        btn20000Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20000DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn20000Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, -1));

        btn50000Dong.setText("50.000đ");
        btn50000Dong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn50000Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50000DongMouseClicked(evt);
            }
        });
        btn50000Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50000DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn50000Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, -1));

        btnBackNapTien.setFont(new java.awt.Font("Cooper", 0, 14)); // NOI18N
        btnBackNapTien.setText("Quay lại");
        btnBackNapTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackNapTienMouseClicked(evt);
            }
        });
        jPanel1.add(btnBackNapTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 100, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 332, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Event click chuột vào button thực thi nạp tiền
    private void btnNapTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNapTienMouseClicked
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtfldNapTien.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Số tiền nạp không được bé hơn 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tiền nạp không hợp lệ");
            return;
        }
        tempTien = kh.getLongSoDu();
        System.out.println("Truoc khi nap " + tempTien);
        tempTien += Integer.parseInt(txtfldNapTien.getText());
        System.out.println("Sau khi nap " + tempTien);
        kh.setLongSoDu(tempTien);
        try {
            khachhangtbl.sua(kh);
            Homepage _homepage = new Homepage();
            dispose();
            _homepage.show();
        } catch (Exception ex) {
            Logger.getLogger(NapTien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnNapTienMouseClicked

    private void txtfldNapTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldNapTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldNapTienActionPerformed

    private void btn100000DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100000DongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn100000DongActionPerformed

    private void btnNapTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNapTienActionPerformed

    private void btn10000DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000DongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10000DongActionPerformed

    private void btn20000DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20000DongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn20000DongActionPerformed

    private void btn50000DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50000DongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn50000DongActionPerformed

    private void btnNapTienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNapTienMouseEntered
        btnNapTien.setBackground(new Color(240, 204, 51));
    }//GEN-LAST:event_btnNapTienMouseEntered

    private void btnNapTienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNapTienMouseExited
        btnNapTien.setBackground(new Color(255, 204, 51));
    }//GEN-LAST:event_btnNapTienMouseExited

    //Event khi click chuột vào button 10.000 đồng.
    private void btn10000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10000DongMouseClicked
        // TODO add your handling code here:
        txtfldNapTien.setText("10000");
    }//GEN-LAST:event_btn10000DongMouseClicked

    //Event khi click chuột vào button 20.000 đồng.
    private void btn20000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20000DongMouseClicked
        // TODO add your handling code here:
        txtfldNapTien.setText("20000");
    }//GEN-LAST:event_btn20000DongMouseClicked
    //Event khi click chuột vào button 50.000 đồng.
    private void btn50000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50000DongMouseClicked
        // TODO add your handling code here:
        txtfldNapTien.setText("50000");
    }//GEN-LAST:event_btn50000DongMouseClicked
    //Event khi click chuột vào button 100.000 đồng.
    private void btn100000DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn100000DongMouseClicked
        // TODO add your handling code here:
        txtfldNapTien.setText("100000");
    }//GEN-LAST:event_btn100000DongMouseClicked

    private void btnBackNapTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackNapTienMouseClicked
        // TODO add your handling code here:
        Homepage _homepage = null;
        try {
            _homepage = new Homepage();
        } catch (Exception ex) {
            Logger.getLogger(NapTien.class.getName()).log(Level.SEVERE, null, ex);
        }
        _homepage.show();
        dispose();
    }//GEN-LAST:event_btnBackNapTienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NapTien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(NapTien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn100000Dong;
    private javax.swing.JToggleButton btn10000Dong;
    private javax.swing.JToggleButton btn20000Dong;
    private javax.swing.JToggleButton btn50000Dong;
    private javax.swing.JButton btnBackNapTien;
    private javax.swing.JButton btnNapTien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtfldNapTien;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/parking.png")));
    }
}
