/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITParking.GUI;

import java.awt.Color;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.swing.JOptionPane;
import static UITParking.GUI.EmailForm.randomOTP;
import UITParking.GUI.ThayDoiMatKhau;
import static UITParking.GUI.EmailForm.pRandomOTP;
import java.awt.Toolkit;
/**
 *
 * @author Pham Hoang Ngoc Anh
 */
 class OTPForm extends javax.swing.JFrame {

    /**
     * Creates new form OTPform
     */
    public OTPForm() {
        initComponents();
        setIconImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOTPModified = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnVerifyOTP = new javax.swing.JButton();
        btnBackOTPForm = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Close_26px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UIT Parking");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("OTP Verification");

        txtOTPModified.setForeground(new java.awt.Color(153, 153, 153));
        txtOTPModified.setText(" Your OTP here...");
        txtOTPModified.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtOTPModified.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOTPModifiedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOTPModifiedFocusLost(evt);
            }
        });
        txtOTPModified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOTPModifiedActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("We have sent OTP to your email");

        btnVerifyOTP.setBackground(new java.awt.Color(12, 33, 250));
        btnVerifyOTP.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnVerifyOTP.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyOTP.setText("Verify OTP");
        btnVerifyOTP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerifyOTP.setBorderPainted(false);
        btnVerifyOTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerifyOTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerifyOTPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerifyOTPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerifyOTPMouseExited(evt);
            }
        });
        btnVerifyOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyOTPActionPerformed(evt);
            }
        });

        btnBackOTPForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-button.png"))); // NOI18N
        btnBackOTPForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackOTPForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackOTPFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBackOTPForm)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtOTPModified, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnVerifyOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnBackOTPForm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtOTPModified, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnVerifyOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOTPModifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOTPModifiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOTPModifiedActionPerformed

    private void txtOTPModifiedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOTPModifiedFocusGained
        // TODO add your handling code here:
        if(txtOTPModified.getText().equals(" Your OTP here...")){
            txtOTPModified.setText("");
            txtOTPModified.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtOTPModifiedFocusGained

    private void txtOTPModifiedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOTPModifiedFocusLost
        // TODO add your handling code here:
        if(txtOTPModified.getText().equals("")){
            txtOTPModified.setText(" Your OTP here...");
            txtOTPModified.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtOTPModifiedFocusLost

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnBackOTPFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackOTPFormMouseClicked
        EmailForm _sentEmail = new EmailForm();
        _sentEmail.show();
        dispose();
    }//GEN-LAST:event_btnBackOTPFormMouseClicked

    private void btnVerifyOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyOTPActionPerformed

    private void btnVerifyOTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyOTPMouseClicked
        // TODO add your handling code here:
        if (Integer.parseInt(txtOTPModified.getText()) == pRandomOTP) {
            JOptionPane.showMessageDialog(null, "OTP chính xác!");
            ThayDoiMatKhau _modifypassword = new ThayDoiMatKhau();
            _modifypassword.show();
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Mã OTP không hợp lệ!");
        }

    }//GEN-LAST:event_btnVerifyOTPMouseClicked

    private void btnVerifyOTPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyOTPMouseEntered
        btnVerifyOTP.setBackground(new Color(80, 60, 244));
    }//GEN-LAST:event_btnVerifyOTPMouseEntered

    private void btnVerifyOTPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyOTPMouseExited
        btnVerifyOTP.setBackground(new Color(12, 33, 250));
    }//GEN-LAST:event_btnVerifyOTPMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTPForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTPForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackOTPForm;
    private javax.swing.JButton btnVerifyOTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtOTPModified;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/parking.png")));

    }
}
