-- Tao bang ChiTietHoaDonMuaVe
create table ChiTietHoaDonMuaVe(
    MaHD varchar2(5),
    MaLoaiVe varchar2(5),
    SoLuongVe Number,
    
    CONSTRAINT PK_CTHD PRIMARY KEY (MaHD, MaLoaiVe)
 );
 
 -- FK CUA ChiTietHoaDonMuaVe
ALTER TABLE ChiTietHoaDonMuaVe ADD CONSTRAINT FK_CTHD_MaHD FOREIGN KEY(MaHD) REFERENCES HoaDonMuave(MaHD);
ALTER TABLE ChiTietHoaDonMuaVe ADD CONSTRAINT FK_CTHD_MaLoaiVe FOREIGN KEY(MaLoaive) REFERENCES LoaiVe(MaLoaiVe);


--Insert ChiTietHoaDonMuaVe Table

INSERT INTO ChiTietHoaDonMuaVe VALUES('HD001', 'LVE01', 3);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD002', 'LVE02', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD003', 'LVE04', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD004', 'LVE02', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD005', 'LVE01', 0);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD006', 'LVE04', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD007', 'LVE04', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD008', 'LVE03', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD009', 'LVE02', 0);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD010', 'LVE04', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD014', 'LVE04', 1);
INSERT INTO ChiTietHoaDonMuaVe VALUES('HD015', 'LVE04', 1);
